# Generated by Django 5.0.7 on 2024-08-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='space',
            new_name='product',
        ),
    ]
