# Generated by Django 5.0.4 on 2024-08-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='response_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
